@HOST = localhost
@PORT = 3001
@VERSION = v1
@URL = http://{{HOST}}:{{PORT}}/api/{{VERSION}}
@TOKEN =

### Create User
POST {{URL}}/users
Content-Type: application/json

{
  "name": "Pedro",
  "email": "p.ed.ro@mail.com",
  "password": "23452324234",
  "role": ""
}

### List Users
GET {{URL}}/users


### Get Of Id
GET {{URL}}/users/:id
Content-Type: application/json

### Softdelete User
DELETE {{URL}}/users/:id

### Undelete User
PATCH {{URL}}/users/:id/restore

# CATEGORY

### Create Category
POST {{URL}}/categories
Content-Type: application/json

{
  "name": "asf"
}

### List Category
GET {{URL}}/categories

### Get Category Of ID
GET {{URL}}/categories/:id

### Search by Name
GET {{URL}}/categories/search?name=

### Softdelete Category
DELETE  {{URL}}/categories/:id

### Undelete Category
PATCH {{URL}}/categories/:id/restore

# PRODUCT

### Create Product
POST {{URL}}/products
Content-Type: application/json

{
  "name": "",
  "price": 9.3,
  "categoryId": "",
  "description": "",
}

### List Products
GET {{URL}}/products

### Get Product of ID
GET {{URL}}/products/:id

### Soft Delete Product
DELETE {{URL}}/products/:id

### Undelete Product
PATCH {{URL}}/products/:id/restore

# REVIEWS

### Create Review
POST {{URL}}/reviews
Content-Type: application/json

{
  "rating": 3,
  "userId": "",
  "productId": ""
}

### Soft Delete Review
DELETE {{URL}}/reviews/:id

# ORDER

### Create Order
POST {{URL}}/orders
Content-Type: application/json

{
  "quantity": 8,
  "unitPrice": 6.8,
  "productId": "",
}

### Get All Orders
GET {{URL}}/orders

### Get Order of Id
GET {{URL}}/orders/id

### Get All Order of User
GET {{URL}}/orders/id/user

### Soft Delete Order
DELETE {{URL}}/orders/id

### Undelete Order
PATCH {{URL}}/orders/id/restore
